/*************************************************************************
    Lab 8 - testmain.cc

	Please do not edit this file in order for your tests to pass.

    This is the driver for your lab. It calls each of the functions.
    Notice here that the one class we wrote works for either integers
    or strings.
    
    John Dolan		    Fall 2014       Ohio University
    Patricia Lindner    October 2021
    Kaeden Saunders 	October 2023	Made the numbers not rand
*************************************************************************/

#include <iostream>
#include "../tarray.h"
using namespace std;

int main(){
    Tarray <int> nums;
    Tarray <string> words;

    nums.add(16);
    nums.add(32);
    nums.add(64);
    nums.add(128);

    for(nums.start(); nums.is_item(); nums.advance())
        cout << nums.current() << endl;

    words.add("CS");
    words.add("is");
    words.add("the");
    words.add("best");
    words.add("major");
    words.add("at");
    words.add("Ohio");
    words.add("University");

    words.start();
    while(words.is_item() && words.current() != "major")
        words.advance();

    words.remove_current();
    for(words.start(); words.is_item(); words.advance())
        cout << words.current() << ' ';

	cout << "\n";
    return 0;
}

