(lang dune 3.1)

(name pa5)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Your name here")

(maintainers "Alex Bagnall")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name pa5)
 (synopsis "PA5")
 (description "PA5")
 (depends ocaml dune)
 (tags (ohio university cs3200 pa5 ocaml)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
