# I had problems with git add commit push -- I think its the token and I haven't resolved it yet ... Manually added code from VSCode

# Task: Implement this Makefile according to the instructions.

# if sandstorm has been touched more recently
calm.txt: sandstorm.txt
	@echo "warning, a sandstorm is active!"