CXXFLAGS=-Wall -g -O0

all: program1 program2 program3

program1: program1.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

program2: program2.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

program3: program3.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
